<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="61.131" tests="6" failures="2">
  <testsuite name="Root Suite" timestamp="2023-08-15T14:34:08" tests="0" file="cypress/e2e/Achats/Suppliers.cy.js" time="0.000" failures="0">
  </testsuite>
  <testsuite name="Suppliers" timestamp="2023-08-15T14:34:08" tests="5" time="30.397" failures="1">
    <testcase name="Suppliers &quot;before all&quot; hook for &quot;Get Suppliers &quot;" time="0.000" classname="&quot;before all&quot; hook for &quot;Get Suppliers &quot;">
      <failure message="`cy.request()` timed out waiting `30000ms` for a response from your server.

The request we sent was:

Method: POST
URL: https://recette-int-qa.facilia.com/login

No response was received within the timeout.

https://on.cypress.io/request

Because this error occurred during a `before all` hook we are skipping the remaining tests in the current suite: `Suppliers`" type="CypressError"><![CDATA[CypressError: `cy.request()` timed out waiting `30000ms` for a response from your server.

The request we sent was:

Method: POST
URL: https://recette-int-qa.facilia.com/login

No response was received within the timeout.

https://on.cypress.io/request

Because this error occurred during a `before all` hook we are skipping the remaining tests in the current suite: `Suppliers`
    at <unknown> (http://localhost:36087/__cypress/runner/cypress_runner.js:149368:78)
    at tryCatcher (http://localhost:36087/__cypress/runner/cypress_runner.js:18744:23)
    at <unknown> (http://localhost:36087/__cypress/runner/cypress_runner.js:13866:41)
    at tryCatcher (http://localhost:36087/__cypress/runner/cypress_runner.js:18744:23)
    at Promise._settlePromiseFromHandler (http://localhost:36087/__cypress/runner/cypress_runner.js:16679:31)
    at Promise._settlePromise (http://localhost:36087/__cypress/runner/cypress_runner.js:16736:18)
    at Promise._settlePromise0 (http://localhost:36087/__cypress/runner/cypress_runner.js:16781:10)
    at Promise._settlePromises (http://localhost:36087/__cypress/runner/cypress_runner.js:16857:18)
    at _drainQueueStep (http://localhost:36087/__cypress/runner/cypress_runner.js:13451:12)
    at _drainQueue (http://localhost:36087/__cypress/runner/cypress_runner.js:13444:9)
    at ../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:36087/__cypress/runner/cypress_runner.js:13460:5)
    at Async.drainQueues (http://localhost:36087/__cypress/runner/cypress_runner.js:13330:14)
From Your Spec Code:
    at Context.ee (webpack:///./node_modules/cypress-plugin-api/dist/support.js:14:2002)]]></failure>
    </testcase>
  </testsuite>
  <testsuite name="Supplier Notes" timestamp="2023-08-15T14:34:39" tests="1" time="30.698" failures="1">
    <testcase name="Supplier Notes &quot;before all&quot; hook for &quot;Get Supplier Families List Notes&quot;" time="0.000" classname="&quot;before all&quot; hook for &quot;Get Supplier Families List Notes&quot;">
      <failure message="`cy.request()` timed out waiting `30000ms` for a response from your server.

The request we sent was:

Method: POST
URL: https://purchase-qa.facilia.com/purchases/companies/2/suppliers

No response was received within the timeout.

https://on.cypress.io/request

Because this error occurred during a `before all` hook we are skipping the remaining tests in the current suite: `Supplier Notes`" type="CypressError"><![CDATA[CypressError: `cy.request()` timed out waiting `30000ms` for a response from your server.

The request we sent was:

Method: POST
URL: https://purchase-qa.facilia.com/purchases/companies/2/suppliers

No response was received within the timeout.

https://on.cypress.io/request

Because this error occurred during a `before all` hook we are skipping the remaining tests in the current suite: `Supplier Notes`
    at <unknown> (http://localhost:36087/__cypress/runner/cypress_runner.js:149368:78)
    at tryCatcher (http://localhost:36087/__cypress/runner/cypress_runner.js:18744:23)
    at <unknown> (http://localhost:36087/__cypress/runner/cypress_runner.js:13866:41)
    at tryCatcher (http://localhost:36087/__cypress/runner/cypress_runner.js:18744:23)
    at Promise._settlePromiseFromHandler (http://localhost:36087/__cypress/runner/cypress_runner.js:16679:31)
    at Promise._settlePromise (http://localhost:36087/__cypress/runner/cypress_runner.js:16736:18)
    at Promise._settlePromise0 (http://localhost:36087/__cypress/runner/cypress_runner.js:16781:10)
    at Promise._settlePromises (http://localhost:36087/__cypress/runner/cypress_runner.js:16857:18)
    at _drainQueueStep (http://localhost:36087/__cypress/runner/cypress_runner.js:13451:12)
    at _drainQueue (http://localhost:36087/__cypress/runner/cypress_runner.js:13444:9)
    at ../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:36087/__cypress/runner/cypress_runner.js:13460:5)
    at Async.drainQueues (http://localhost:36087/__cypress/runner/cypress_runner.js:13330:14)
From Your Spec Code:
    at Context.ee (webpack:///./node_modules/cypress-plugin-api/dist/support.js:14:2002)]]></failure>
    </testcase>
  </testsuite>
</testsuites>